@startuml

entity Users{
id
name
email
password
image_path
created_at
modified_at
}

entity Groups
{
id
name
created_at
modified_at
}

entity Laundries{
id
group_id
name
description
days_for_wash
message_for_notice
}

entity Assigned{
landry_id
user_id
is_approved
is_fixed
message_for_notice
}

Users ||--o| Groups
Groups ||-o{ Laundries
Laundries ||-|| Assigned
Users }o--|| Assigned


@enduml
